version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zliangcheng
      POSTGRES_PASSWORD: zliangcheng9628
      POSTGRES_DB: demo_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: